//! The secret key: where it is, and where a first one comes from.
//!
//! No key format is invented and no key is stored in the store. The default is
//! minisign's own — `~/.minisign/minisign.key` — so a key generated by
//! `minisign -G` years ago works here with nothing done to it, and one
//! generated here is one the `minisign` command will pick up unchanged if that
//! is ever installed.
//!
//! [`generate`] exists at all because the alternative is telling somebody their
//! first signature requires installing a C program, and a trust layer nobody
//! starts using protects nothing. Decision 0001 says so; decision 0002 is why
//! the code is here rather than in a subprocess.
//!
//! This module reaches `std::fs` directly rather than through Historica's
//! filesystem seam. The seam is about the store, and a secret key is the one
//! file in this design that must never be in one.

use std::fmt;
use std::fs::{self, File};
use std::io;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use minisign::{KeyPair, PublicKey, SecretKey};

use crate::claim::Key;

/// The directory minisign keeps its keys in, under the home directory.
pub const KEY_DIR: &str = ".minisign";

/// What minisign calls a secret key.
pub const SECRET_KEY_FILE: &str = "minisign.key";

/// What minisign calls a public key.
pub const PUBLIC_KEY_FILE: &str = "minisign.pub";

/// Where a secret key is when nobody said otherwise.
///
/// `None` when the platform will not say where home is, which is a question
/// about the machine rather than about the store — a caller that has its own
/// answer passes a path instead.
pub fn default_secret_key() -> Option<PathBuf> {
    home().map(|home| home.join(KEY_DIR).join(SECRET_KEY_FILE))
}

/// Load a secret key.
///
/// `password` of `None` means an encrypted key prompts for one on the terminal,
/// which is minisign's own behaviour and the reason this is not a function that
/// takes a password out of the environment: a secret that has to sit in a
/// variable to be used is a secret that ends up in a shell history.
pub fn load(path: &Path, password: Option<String>) -> Result<SecretKey, KeyError> {
    if !path.exists() {
        return Err(KeyError::NoKey {
            path: path.to_path_buf(),
        });
    }
    SecretKey::from_file(path, password).map_err(|error| KeyError::Minisign {
        because: error.to_string(),
    })
}

/// A password read from a file, or from standard input when `path` is `-`.
///
/// The one way to sign without a terminal. A password in an environment
/// variable ends up in a shell history and in every child process's
/// environment; a file can be a mounted secret, a pipe, or a `/dev/fd` the
/// shell made, and it is the caller's business which. Exactly one trailing
/// newline is removed, because a file written by `echo` has one and a password
/// with a newline in it cannot be typed at minisign's own prompt anyway.
pub fn password_from(path: &Path) -> Result<String, KeyError> {
    let text = if path == Path::new("-") {
        io::read_to_string(io::stdin()).map_err(|error| KeyError::io(path, error))?
    } else {
        fs::read_to_string(path).map_err(|error| KeyError::io(path, error))?
    };
    Ok(text.strip_suffix('\n').unwrap_or(&text).to_owned())
}

/// The public key a secret key belongs to, spelled as a claim spells it.
pub fn public_of(secret: &SecretKey) -> Result<Key, KeyError> {
    let public = PublicKey::from_secret_key(secret).map_err(|error| KeyError::Minisign {
        because: error.to_string(),
    })?;
    public
        .to_base64()
        .parse()
        .map_err(|error: crate::claim::MalformedKey| KeyError::Minisign {
            because: error.to_string(),
        })
}

/// A key pair, freshly written.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Generated {
    /// Where the secret key is.
    pub secret: PathBuf,
    /// Where the public key is.
    pub public: PathBuf,
    /// The public key itself, which is the line that goes in a trust entry.
    pub key: Key,
}

/// Generate a minisign key pair in `directory`.
///
/// `password` of `None` prompts for one twice, as `minisign -G` does. Neither
/// file is overwritten: a secret key already at that path stops this, because
/// overwriting one destroys every signature it ever made and there is no
/// undoing it.
pub fn generate(directory: &Path, password: Option<String>) -> Result<Generated, KeyError> {
    let secret = directory.join(SECRET_KEY_FILE);
    let public = directory.join(PUBLIC_KEY_FILE);
    for path in [&secret, &public] {
        if path.exists() {
            return Err(KeyError::Taken { path: path.clone() });
        }
    }

    fs::create_dir_all(directory).map_err(|error| KeyError::io(directory, error))?;

    // Written to memory first, then to disk with `create_new`: the check above
    // is a courtesy that says something useful, and this is what makes the
    // refusal true even if a key appeared in between.
    let mut public_bytes = Vec::new();
    let mut secret_bytes = Vec::new();
    let pair = KeyPair::generate_and_write_encrypted_keypair(
        &mut public_bytes,
        &mut secret_bytes,
        None,
        password,
    )
    .map_err(|error| KeyError::Minisign {
        because: error.to_string(),
    })?;

    create_new(&public, &public_bytes)?;
    if let Err(error) = create_new(&secret, &secret_bytes) {
        // The public key is half a pair and useless alone; leaving it would
        // have somebody paste it into a trust entry no key can ever sign for.
        let _ = fs::remove_file(&public);
        return Err(error);
    }

    let key = pair
        .pk
        .to_base64()
        .parse()
        .map_err(|error: crate::claim::MalformedKey| KeyError::Minisign {
            because: error.to_string(),
        })?;

    Ok(Generated {
        secret,
        public,
        key,
    })
}

fn create_new(path: &Path, bytes: &[u8]) -> Result<(), KeyError> {
    let mut file = File::create_new(path).map_err(|error| match error.kind() {
        io::ErrorKind::AlreadyExists => KeyError::Taken {
            path: path.to_path_buf(),
        },
        _ => KeyError::io(path, error),
    })?;
    file.write_all(bytes)
        .and_then(|()| file.flush())
        .map_err(|error| KeyError::io(path, error))
}

fn home() -> Option<PathBuf> {
    for name in ["HOME", "USERPROFILE"] {
        if let Some(value) = std::env::var_os(name)
            && !value.is_empty()
        {
            return Some(PathBuf::from(value));
        }
    }
    None
}

/// Why a key could not be read or written.
#[derive(Debug)]
#[non_exhaustive]
pub enum KeyError {
    /// There is no key at that path.
    NoKey {
        /// Where one was looked for.
        path: PathBuf,
    },
    /// A file is already there, and this will not overwrite one.
    Taken {
        /// The file.
        path: PathBuf,
    },
    /// minisign refused.
    Minisign {
        /// What it said.
        because: String,
    },
    /// The filesystem refused.
    Io {
        /// What was being read or written.
        path: PathBuf,
        /// What it said.
        error: io::Error,
    },
}

impl KeyError {
    fn io(path: &Path, error: io::Error) -> Self {
        Self::Io {
            path: path.to_path_buf(),
            error,
        }
    }
}

impl fmt::Display for KeyError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NoKey { path } => write!(
                f,
                "there is no key at {}; `historica-sign key new` writes one, \
                 and `--key` names one somewhere else",
                path.display()
            ),
            Self::Taken { path } => write!(
                f,
                "{} is already there, and a key is never overwritten: doing so \
                 destroys every signature it ever made",
                path.display()
            ),
            Self::Minisign { because } => write!(f, "minisign: {because}"),
            Self::Io { path, error } => write!(f, "{}: {error}", path.display()),
        }
    }
}

impl std::error::Error for KeyError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io { error, .. } => Some(error),
            _ => None,
        }
    }
}
